let questions = [
  { id: 1, question: "What is the capital city of France?", answer: "Paris", type: "general" },
  { id: 2, question: "Which planet is known as the Red Planet?", answer: "Mars", type: "general" },
  { id: 3, question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci", type: "general" },
  { id: 4, question: "What is the largest ocean on Earth?", answer: "Pacific Ocean", type: "general" },
  { id: 5, question: "In which year did the Titanic sink?", answer: "1912", type: "general" },
  { id: 6, question: "What is the chemical symbol for gold?", answer: "Au", type: "general" },
  { id: 7, question: "Who developed the theory of relativity?", answer: "Albert Einstein", type: "general" },
  { id: 8, question: "Which country hosted the 2016 Summer Olympics?", answer: "Brazil", type: "general" },
  { id: 9, question: "What is the largest mammal in the world?", answer: "Blue whale", type: "general" },
  { id: 10, question: "How many continents are there on Earth?", answer: "Seven", type: "general" },
  { id: 11, question: "What is the square root of 144?", answer: "12", type: "general" },
  { id: 12, question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare", type: "general" },
  { id: 13, question: "Which element has the chemical symbol O?", answer: "Oxygen", type: "general" },
  { id: 14, question: "What is the tallest mountain in the world?", answer: "Mount Everest", type: "general" },
  { id: 15, question: "Which planet is closest to the Sun?", answer: "Mercury", type: "general" },
  { id: 16, question: "What is the smallest prime number?", answer: "2", type: "general" },
  { id: 17, question: "Who was the first person to walk on the Moon?", answer: "Neil Armstrong", type: "general" },
  { id: 18, question: "Which country is known as the Land of the Rising Sun?", answer: "Japan", type: "general" },
  { id: 19, question: "What is H2O commonly known as?", answer: "Water", type: "general" },
  { id: 20, question: "Which planet has a ring system?", answer: "Saturn", type: "general" },
  { id: 21, question: "What is the currency of the United States?", answer: "Dollar", type: "general" },
  { id: 22, question: "Who is the author of 'Harry Potter' series?", answer: "J.K. Rowling", type: "general" },
  { id: 23, question: "Which gas do plants absorb from the atmosphere?", answer: "Carbon dioxide", type: "general" },
  { id: 24, question: "What is the hardest natural substance on Earth?", answer: "Diamond", type: "general" },
  { id: 25, question: "Which organ pumps blood throughout the human body?", answer: "Heart", type: "general" },
  { id: 26, question: "Which ocean is the smallest on Earth?", answer: "Arctic Ocean", type: "general" },
  { id: 27, question: "Who painted the Starry Night?", answer: "Vincent van Gogh", type: "general" },
  { id: 28, question: "What is the freezing point of water in Celsius?", answer: "0", type: "general" },
  { id: 29, question: "Which planet is called the Morning Star?", answer: "Venus", type: "general" },
  { id: 30, question: "What is the main language spoken in Brazil?", answer: "Portuguese", type: "general" },
  { id: 31, question: "What is the capital of Italy?", answer: "Rome", type: "general" },
  { id: 32, question: "Who discovered penicillin?", answer: "Alexander Fleming", type: "general" },
  { id: 33, question: "What is the largest desert in the world?", answer: "Sahara Desert", type: "general" },
  { id: 34, question: "Which instrument has keys, pedals, and strings?", answer: "Piano", type: "general" },
  { id: 35, question: "How many players are on a soccer team on the field?", answer: "11", type: "general" },
  { id: 36, question: "What is the chemical symbol for sodium?", answer: "Na", type: "general" },
  { id: 37, question: "Which animal is known as the King of the Jungle?", answer: "Lion", type: "general" },
  { id: 38, question: "Who was the first President of the United States?", answer: "George Washington", type: "general" },
  { id: 39, question: "What is the longest river in the world?", answer: "Nile River", type: "general" },
  { id: 40, question: "In which country were the Olympic Games invented?", answer: "Greece", type: "general" },
  { id: 41, question: "What color do you get when you mix red and blue?", answer: "Purple", type: "general" },
  { id: 42, question: "What part of the plant conducts photosynthesis?", answer: "Leaf", type: "general" },
  { id: 43, question: "How many sides does a hexagon have?", answer: "Six", type: "general" },
  { id: 44, question: "Who wrote 'The Lord of the Rings'?", answer: "J.R.R. Tolkien", type: "general" },
  { id: 45, question: "Which ocean lies between Africa and Australia?", answer: "Indian Ocean", type: "general" },
  { id: 46, question: "What is the boiling point of water in Celsius?", answer: "100", type: "general" },
  { id: 47, question: "Who invented the telephone?", answer: "Alexander Graham Bell", type: "general" },
  { id: 48, question: "Which country has the maple leaf on its flag?", answer: "Canada", type: "general" },
  { id: 49, question: "What is the largest land animal?", answer: "Elephant", type: "general" },
  { id: 50, question: "Who painted the ceiling of the Sistine Chapel?", answer: "Michelangelo", type: "general" },
  { id: 51, question: "Which planet is known for its Great Red Spot?", answer: "Jupiter", type: "general" },
  { id: 52, question: "In which sport is the term 'love' used?", answer: "Tennis", type: "general" },
  { id: 53, question: "What is the capital of Spain?", answer: "Madrid", type: "general" },
  { id: 54, question: "Who discovered gravity?", answer: "Isaac Newton", type: "general" },
  { id: 55, question: "What is the fastest land animal?", answer: "Cheetah", type: "general" },
  { id: 56, question: "Which bird can mimic human speech?", answer: "Parrot", type: "general" },
  { id: 57, question: "What is the largest internal organ in the human body?", answer: "Liver", type: "general" },
  { id: 58, question: "What is the national flower of Japan?", answer: "Cherry blossom", type: "general" },
  { id: 59, question: "Who invented the light bulb?", answer: "Thomas Edison", type: "general" },
  { id: 60, question: "Which country is home to the kangaroo?", answer: "Australia", type: "general" },
  { id: 61, question: "What is the tallest building in the world (as of 2024)?", answer: "Burj Khalifa", type: "general" },
  { id: 62, question: "How many bones are in the adult human body?", answer: "206", type: "general" },
  { id: 63, question: "Which country has the city of Istanbul?", answer: "Turkey", type: "general" },
  { id: 64, question: "What is the main ingredient in guacamole?", answer: "Avocado", type: "general" },
  { id: 65, question: "What is the capital of Canada?", answer: "Ottawa", type: "general" },
  { id: 66, question: "Who is known as the Father of Computers?", answer: "Charles Babbage", type: "general" },
  { id: 67, question: "Which metal is liquid at room temperature?", answer: "Mercury", type: "general" },
  { id: 68, question: "How many legs does a spider have?", answer: "Eight", type: "general" },
  { id: 69, question: "What is the largest planet in our solar system?", answer: "Jupiter", type: "general" },
  { id: 70, question: "Who painted 'The Persistence of Memory'?", answer: "Salvador Dalí", type: "general" },
  { id: 71, question: "What is the capital of Germany?", answer: "Berlin", type: "general" },
  { id: 72, question: "Which organ helps you breathe?", answer: "Lungs", type: "general" },
  { id: 73, question: "What is the capital of Russia?", answer: "Moscow", type: "general" },
  { id: 74, question: "Which is the largest continent on Earth?", answer: "Asia", type: "general" },
  { id: 75, question: "Who invented the World Wide Web?", answer: "Tim Berners-Lee", type: "general" },
  { id: 76, question: "Which element has the symbol Fe?", answer: "Iron", type: "general" },
  { id: 77, question: "How many days are there in a leap year?", answer: "366", type: "general" },
  { id: 78, question: "Which country gifted the Statue of Liberty to the USA?", answer: "France", type: "general" },
  { id: 79, question: "What is the largest island in the world?", answer: "Greenland", type: "general" },
  { id: 80, question: "What is the capital city of Egypt?", answer: "Cairo", type: "general" },
  { id: 81, question: "Who was known as the Maid of Orléans?", answer: "Joan of Arc", type: "general" },
  { id: 82, question: "Which instrument is used to measure temperature?", answer: "Thermometer", type: "general" },
  { id: 83, question: "What is the national currency of Japan?", answer: "Yen", type: "general" },
  { id: 84, question: "How many colors are there in a rainbow?", answer: "Seven", type: "general" },
  { id: 85, question: "Which planet has the most moons?", answer: "Saturn", type: "general" },
  { id: 86, question: "Who painted 'Girl with a Pearl Earring'?", answer: "Johannes Vermeer", type: "general" },
  { id: 87, question: "What is the largest bone in the human body?", answer: "Femur", type: "general" },
  { id: 88, question: "Which country is famous for the Eiffel Tower?", answer: "France", type: "general" },
  { id: 89, question: "What is the study of earthquakes called?", answer: "Seismology", type: "general" },
  { id: 90, question: "Who was the Greek god of the sea?", answer: "Poseidon", type: "general" },
  { id: 91, question: "What is the chemical symbol for silver?", answer: "Ag", type: "general" },
  { id: 92, question: "Which animal is known to have nine lives?", answer: "Cat", type: "general" },
  { id: 93, question: "How many players are there on a basketball team on the court?", answer: "Five", type: "general" },
  { id: 94, question: "What is the main gas found in the Earth's atmosphere?", answer: "Nitrogen", type: "general" },
  { id: 95, question: "Which city is known as the Big Apple?", answer: "New York City", type: "general" },
  { id: 96, question: "Who wrote 'The Odyssey'?", answer: "Homer", type: "general" },
  { id: 97, question: "Which planet is known for its rings?", answer: "Saturn", type: "general" },
  { id: 98, question: "What is the largest coral reef system in the world?", answer: "Great Barrier Reef", type: "general" },
  { id: 99, question: "Who discovered America in 1492?", answer: "Christopher Columbus", type: "general" },
  { id: 101, question: "What is the capital of Australia?", answer: "Canberra", type: "general" },
{ id: 102, question: "Which country is famous for pizza and pasta?", answer: "Italy", type: "general" },
{ id: 103, question: "Who discovered gravity?", answer: "Isaac Newton", type: "general" },
{ id: 104, question: "What is the largest planet in the solar system?", answer: "Jupiter", type: "general" },
{ id: 105, question: "Who was the first man to walk on the Moon?", answer: "Neil Armstrong", type: "general" },
{ id: 106, question: "What is the fastest land animal?", answer: "Cheetah", type: "general" },
{ id: 107, question: "Which ocean is on the east coast of the United States?", answer: "Atlantic Ocean", type: "general" },
{ id: 108, question: "What is the currency of Japan?", answer: "Yen", type: "general" },
{ id: 109, question: "Who wrote 'Harry Potter'?", answer: "J.K. Rowling", type: "general" },
{ id: 110, question: "Which fruit is known to keep the doctor away?", answer: "Apple", type: "general" },
{ id: 111, question: "What is the capital of Germany?", answer: "Berlin", type: "general" },
{ id: 112, question: "Which bird is known for its colorful tail feathers?", answer: "Peacock", type: "general" },
{ id: 113, question: "What gas do humans exhale when they breathe?", answer: "Carbon dioxide", type: "general" },
{ id: 114, question: "What is the most popular sport in the world?", answer: "Football (Soccer)", type: "general" },
{ id: 115, question: "Which continent is Egypt part of?", answer: "Africa", type: "general" },
{ id: 116, question: "What is the name of the fairy in Peter Pan?", answer: "Tinker Bell", type: "general" },
{ id: 117, question: "Which planet is closest to the Sun?", answer: "Mercury", type: "general" },
{ id: 118, question: "What is the main ingredient in bread?", answer: "Flour", type: "general" },
{ id: 119, question: "What is the national animal of China?", answer: "Giant Panda", type: "general" },
{ id: 120, question: "What color are emeralds?", answer: "Green", type: "general" },
{ id: 121, question: "Which Disney movie features the song 'Let It Go'?", answer: "Frozen", type: "general" },
{ id: 122, question: "What is the capital of Mexico?", answer: "Mexico City", type: "general" },
{ id: 123, question: "What is the largest ocean in the world?", answer: "Pacific Ocean", type: "general" },
{ id: 124, question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci", type: "general" },
{ id: 125, question: "Which instrument has black and white keys?", answer: "Piano", type: "general" },
{ id: 126, question: "What do bees produce?", answer: "Honey", type: "general" },
{ id: 127, question: "Which planet is famous for its rings?", answer: "Saturn", type: "general" },
{ id: 128, question: "Who is known as the King of Pop?", answer: "Michael Jackson", type: "general" },
{ id: 129, question: "What is the capital of China?", answer: "Beijing", type: "general" },
{ id: 130, question: "Which animal gives us wool?", answer: "Sheep", type: "general" },
{ id: 131, question: "Which country is known for the Great Wall?", answer: "China", type: "general" },
{ id: 132, question: "What is the main ingredient in sushi?", answer: "Rice", type: "general" },
{ id: 133, question: "What planet do we live on?", answer: "Earth", type: "general" },
{ id: 134, question: "How many legs does a butterfly have?", answer: "Six", type: "general" },
{ id: 135, question: "Which sea creature has eight arms?", answer: "Octopus", type: "general" },
{ id: 136, question: "What is the color of the sky on a clear day?", answer: "Blue", type: "general" },
{ id: 137, question: "Which animal is known for its trunk?", answer: "Elephant", type: "general" },
{ id: 138, question: "What shape is used for stop signs?", answer: "Octagon", type: "general" },
{ id: 139, question: "What is the capital of India?", answer: "New Delhi", type: "general" },
{ id: 140, question: "How many hours are in a day?", answer: "24", type: "general" },
{ id: 141, question: "Which planet is known as the Blue Planet?", answer: "Earth", type: "general" },
{ id: 142, question: "Which animal is known as man's best friend?", answer: "Dog", type: "general" },
{ id: 143, question: "Which country is home to the Eiffel Tower?", answer: "France", type: "general" },
{ id: 144, question: "What is the largest country in the world by area?", answer: "Russia", type: "general" },
{ id: 145, question: "Which natural satellite orbits the Earth?", answer: "Moon", type: "general" },
{ id: 146, question: "What color do you get by mixing red and yellow?", answer: "Orange", type: "general" },
{ id: 147, question: "What is the opposite of 'hot'?", answer: "Cold", type: "general" },
{ id: 148, question: "What do you call a baby cat?", answer: "Kitten", type: "general" },
{ id: 149, question: "What is the capital of the United Kingdom?", answer: "London", type: "general" },
{ id: 150, question: "Which planet is farthest from the Sun?", answer: "Neptune", type: "general" },
];

window.QUESTIONS = questions;
