let questions = [
   { id: 1, question: "What is the capital city of France?", answer: ["Paris"], type: "general" },
  { id: 2, question: "Which planet is known as the Red Planet?", answer: ["Mars"], type: "general" },
  { id: 3, question: "Who painted the Mona Lisa?", answer: ["Leonardo da Vinci", "Da Vinci"], type: "general" },
  { id: 4, question: "What is the largest ocean on Earth?", answer: ["Pacific Ocean", "Pacific"], type: "general" },
  { id: 5, question: "In which year did the Titanic sink?", answer: ["1912"], type: "general" },
  { id: 6, question: "What is the chemical symbol for gold?", answer: ["Au"], type: "general" },
  { id: 7, question: "Who developed the theory of relativity?", answer: ["Albert Einstein", "Einstein"], type: "general" },
  { id: 8, question: "Which country hosted the 2016 Summer Olympics?", answer: ["Brazil"], type: "general" },
  { id: 9, question: "What is the largest mammal in the world?", answer: ["Blue whale", "Whale"], type: "general" },
  { id: 10, question: "How many continents are there on Earth?", answer: ["7", "seven"], type: "general" },
  { id: 11, question: "What is the square root of 144?", answer: ["12", "twelve"], type: "general" },
  { id: 12, question: "Who wrote 'Romeo and Juliet'?", answer: ["William Shakespeare", "Shakespeare"], type: "general" },
  { id: 13, question: "Which element has the chemical symbol O?", answer: ["Oxygen"], type: "general" },
  { id: 14, question: "What is the tallest mountain in the world?", answer: ["Mount Everest", "Mt Everest", "Everest"], type: "general" },
  { id: 15, question: "Which planet is closest to the Sun?", answer: ["Mercury"], type: "general" },
  { id: 16, question: "What is the smallest prime number?", answer: ["2", "two"], type: "general" },
  { id: 17, question: "Who was the first person to walk on the Moon?", answer: ["Neil Armstrong", "Armstrong"], type: "general" },
  { id: 18, question: "Which country is known as the Land of the Rising Sun?", answer: ["Japan"], type: "general" },
  { id: 19, question: "What is H2O commonly known as?", answer: ["Water"], type: "general" },
  { id: 20, question: "Which planet has a ring system?", answer: ["Saturn"], type: "general" },
  { id: 21, question: "What is the currency of the United States?", answer: ["Dollar", "US Dollar", "USD"], type: "general" },
  { id: 22, question: "Who is the author of 'Harry Potter' series?", answer: ["J.K. Rowling", "JK Rowling", "J K Rowling"], type: "general" },
  { id: 23, question: "Which gas do plants absorb from the atmosphere?", answer: ["Carbon dioxide", "CO2"], type: "general" },
  { id: 24, question: "What is the hardest natural substance on Earth?", answer: ["Diamond"], type: "general" },
  { id: 25, question: "Which organ pumps blood throughout the human body?", answer: ["Heart"], type: "general" },
  { id: 26, question: "Which ocean is the smallest on Earth?", answer: ["Arctic Ocean", "Arctic"], type: "general" },
  { id: 27, question: "Who painted the Starry Night?", answer: ["Vincent van Gogh", "Van Gogh"], type: "general" },
  { id: 28, question: "What is the freezing point of water in Celsius?", answer: ["0", "zero"], type: "general" },
  { id: 29, question: "Which planet is called the Morning Star?", answer: ["Venus"], type: "general" },
  { id: 30, question: "What is the main language spoken in Brazil?", answer: ["Portuguese"], type: "general" },
  { id: 31, question: "What is the capital of Italy?", answer: ["Rome"], type: "general" },
  { id: 32, question: "Who discovered penicillin?", answer: ["Alexander Fleming", "Fleming"], type: "general" },
  { id: 33, question: "What is the largest desert in the world?", answer: ["Sahara Desert", "Sahara"], type: "general" },
  { id: 34, question: "Which instrument has keys, pedals, and strings?", answer: ["Piano"], type: "general" },
  { id: 35, question: "How many players are on a soccer team on the field?", answer: ["11", "eleven"], type: "general" },
  { id: 36, question: "What is the chemical symbol for sodium?", answer: ["Na"], type: "general" },
  { id: 37, question: "Which animal is known as the King of the Jungle?", answer: ["Lion"], type: "general" },
  { id: 38, question: "Who was the first President of the United States?", answer: ["George Washington", "Washington"], type: "general" },
  { id: 39, question: "What is the longest river in the world?", answer: ["Nile", "River Nile"], type: "general" },
  { id: 40, question: "In which country were the Olympic Games invented?", answer: ["Greece"], type: "general" },
  { id: 41, question: "What color do you get when you mix red and blue?", answer: ["Purple", "Violet"], type: "general" },
  { id: 42, question: "What part of the plant conducts photosynthesis?", answer: ["Leaf", "Leaves"], type: "general" },
  { id: 43, question: "How many sides does a hexagon have?", answer: ["Six", "6"], type: "general" },
  { id: 44, question: "Who wrote 'The Lord of the Rings'?", answer: ["J.R.R. Tolkien", "JRR Tolkien", "Tolkien"], type: "general" },
  { id: 45, question: "Which ocean lies between Africa and Australia?", answer: ["Indian Ocean", "Indian"], type: "general" },
  { id: 46, question: "What is the boiling point of water in Celsius?", answer: ["100", "hundred"], type: "general" },
  { id: 47, question: "Who invented the telephone?", answer: ["Alexander Graham Bell", "Graham Bell", "Bell"], type: "general" },
  { id: 48, question: "Which country has the maple leaf on its flag?", answer: ["Canada"], type: "general" },
  { id: 49, question: "What is the largest land animal?", answer: ["Elephant"], type: "general" },
  { id: 50, question: "Who painted the ceiling of the Sistine Chapel?", answer: ["Michelangelo"], type: "general" },
   { id: 51, question: "What is the capital of Japan?", answer: ["Tokyo"], type: "general" },
  { id: 52, question: "What is the largest planet in our solar system?", answer: ["Jupiter"], type: "general" },
  { id: 53, question: "Who discovered America in 1492?", answer: ["Christopher Columbus", "Columbus"], type: "general" },
  { id: 54, question: "What is the main ingredient in guacamole?", answer: ["Avocado"], type: "general" },
  { id: 55, question: "Which bird is known for its colorful feathers and mimicking sounds?", answer: ["Parrot"], type: "general" },
  { id: 56, question: "Which blood type is known as the universal donor?", answer: ["O negative", "O-"], type: "general" },
  { id: 57, question: "Which metal is liquid at room temperature?", answer: ["Mercury"], type: "general" },
  { id: 58, question: "Who is known as the Father of Computers?", answer: ["Charles Babbage", "Babbage"], type: "general" },
  { id: 59, question: "Which planet is known for its Great Red Spot?", answer: ["Jupiter"], type: "general" },
  { id: 60, question: "What is the most spoken language in the world?", answer: ["English"], type: "general" },
  { id: 61, question: "What is the capital of Spain?", answer: ["Madrid"], type: "general" },
  { id: 62, question: "How many bones are in the adult human body?", answer: ["206"], type: "general" },
  { id: 63, question: "What is the process by which plants make their food?", answer: ["Photosynthesis"], type: "general" },
  { id: 64, question: "Who wrote 'The Adventures of Sherlock Holmes'?", answer: ["Arthur Conan Doyle", "Conan Doyle", "Doyle"], type: "general" },
  { id: 65, question: "Which ocean borders the east coast of the United States?", answer: ["Atlantic Ocean", "Atlantic"], type: "general" },
  { id: 66, question: "What is the capital of Germany?", answer: ["Berlin"], type: "general" },
  { id: 67, question: "Who invented the light bulb?", answer: ["Thomas Edison", "Edison"], type: "general" },
  { id: 68, question: "What gas do humans need to breathe?", answer: ["Oxygen"], type: "general" },
  { id: 69, question: "Which natural satellite orbits the Earth?", answer: ["The Moon", "Moon"], type: "general" },
  { id: 70, question: "What is the largest internal organ in the human body?", answer: ["Liver"], type: "general" },
  { id: 71, question: "What is the main ingredient in bread?", answer: ["Flour"], type: "general" },
  { id: 72, question: "Which planet is known for its rings?", answer: ["Saturn"], type: "general" },
  { id: 73, question: "Who wrote 'Pride and Prejudice'?", answer: ["Jane Austen", "Austen"], type: "general" },
  { id: 74, question: "What is the capital city of Australia?", answer: ["Canberra"], type: "general" },
  { id: 75, question: "How many colors are in a rainbow?", answer: ["7", "seven"], type: "general" },
  { id: 76, question: "Who was the Greek god of the sea?", answer: ["Poseidon"], type: "general" },
  { id: 77, question: "Which planet is second from the Sun?", answer: ["Venus"], type: "general" },
  { id: 78, question: "What is the capital of Canada?", answer: ["Ottawa"], type: "general" },
  { id: 79, question: "Which organ helps in breathing?", answer: ["Lungs"], type: "general" },
  { id: 80, question: "What is the national flower of Japan?", answer: ["Cherry blossom", "Sakura"], type: "general" },
  { id: 81, question: "What is the capital of Russia?", answer: ["Moscow"], type: "general" },
  { id: 82, question: "Which planet is known as the Blue Planet?", answer: ["Earth"], type: "general" },
  { id: 83, question: "How many players are on a basketball team on the court?", answer: ["5", "five"], type: "general" },
  { id: 84, question: "Which is the fastest land animal?", answer: ["Cheetah"], type: "general" },
  { id: 85, question: "What is the name of the galaxy that Earth is in?", answer: ["Milky Way", "Milky Way Galaxy"], type: "general" },
  { id: 86, question: "Which ocean is on the west coast of the United States?", answer: ["Pacific Ocean", "Pacific"], type: "general" },
  { id: 87, question: "What is the capital of China?", answer: ["Beijing"], type: "general" },
  { id: 89, question: "What is the chemical symbol for iron?", answer: ["Fe"], type: "general" },
  { id: 90, question: "Who painted the Last Supper?", answer: ["Leonardo da Vinci", "Da Vinci"], type: "general" },
  { id: 91, question: "What is the capital of South Korea?", answer: ["Seoul"], type: "general" },
  { id: 92, question: "Which instrument has strings and is played with a bow?", answer: ["Violin"], type: "general" },
  { id: 93, question: "How many days are there in a leap year?", answer: ["366"], type: "general" },
  { id: 94, question: "What is the capital of Mexico?", answer: ["Mexico City"], type: "general" },
  { id: 95, question: "Who discovered gravity?", answer: ["Isaac Newton", "Newton"], type: "general" },
  { id: 96, question: "Which planet has the most moons?", answer: ["Saturn"], type: "general" },
  { id: 97, question: "Which country gifted the Statue of Liberty to the USA?", answer: ["France"], type: "general" },
  { id: 98, question: "What is the capital of Egypt?", answer: ["Cairo"], type: "general" },
  { id: 99, question: "Who was the first man to reach the South Pole?", answer: ["Roald Amundsen", "Amundsen"], type: "general" },
  { id: 100, question: "Which continent is the Sahara Desert located in?", answer: ["Africa"], type: "general" },
  { id: 101, question: "What is the tallest building in the world (as of 2024)?", answer: ["Burj Khalifa", "Khalifa Tower"], type: "general" },
   { id: 102, question: "Which animal is the largest reptile?", answer: ["Crocodile"], type: "general" },
  { id: 103, question: "What is the process of water turning into vapor called?", answer: ["Evaporation"], type: "general" },
  { id: 104, question: "Who was the first woman to win a Nobel Prize?", answer: ["Marie Curie", "Curie"], type: "general" },
  { id: 105, question: "Which is the smallest country in the world?", answer: ["Vatican City"], type: "general" },
  { id: 106, question: "What is the capital of India?", answer: ["New Delhi", "Delhi"], type: "general" },
  { id: 107, question: "Which continent is known as the Dark Continent?", answer: ["Africa"], type: "general" },
  { id: 108, question: "What is the most abundant gas in Earth’s atmosphere?", answer: ["Nitrogen"], type: "general" },
  { id: 109, question: "Who invented the airplane?", answer: ["Wright brothers", "Orville and Wilbur Wright"], type: "general" },
  { id: 110, question: "What is the largest island in the world?", answer: ["Greenland"], type: "general" },
  { id: 111, question: "Who wrote 'The Odyssey'?", answer: ["Homer"], type: "general" },
  { id: 112, question: "Which planet is known as the Gas Giant?", answer: ["Jupiter"], type: "general" },
  { id: 113, question: "What is the main gas found in the air we breathe?", answer: ["Nitrogen"], type: "general" },
  { id: 114, question: "What is the capital of Argentina?", answer: ["Buenos Aires"], type: "general" },
  { id: 115, question: "Who painted 'The Persistence of Memory'?", answer: ["Salvador Dali", "Dali"], type: "general" },
  { id: 116, question: "Which country is known for pizza and pasta?", answer: ["Italy"], type: "general" },
  { id: 117, question: "What is the largest bone in the human body?", answer: ["Femur", "Thigh bone"], type: "general" },
  { id: 118, question: "Which animal is known for its black and white stripes?", answer: ["Zebra"], type: "general" },
  { id: 119, question: "Who was the first man in space?", answer: ["Yuri Gagarin", "Gagarin"], type: "general" },
  { id: 120, question: "Which country has the Great Wall?", answer: ["China"], type: "general" },
  { id: 121, question: "What is the capital of Portugal?", answer: ["Lisbon"], type: "general" },
  { id: 122, question: "Who developed the theory of evolution?", answer: ["Charles Darwin", "Darwin"], type: "general" },
  { id: 123, question: "What is the largest city in the United States?", answer: ["New York City", "New York"], type: "general" },
  { id: 124, question: "What is the main ingredient in sushi?", answer: ["Rice"], type: "general" },
  { id: 125, question: "Which continent is the coldest?", answer: ["Antarctica"], type: "general" },
  { id: 126, question: "What is the capital of the United Kingdom?", answer: ["London"], type: "general" },
  { id: 127, question: "Who painted 'Girl with a Pearl Earring'?", answer: ["Johannes Vermeer", "Vermeer"], type: "general" },
  { id: 128, question: "Which ocean surrounds the Maldives?", answer: ["Indian Ocean", "Indian"], type: "general" },
  { id: 129, question: "Which blood cells help fight infection?", answer: ["White blood cells", "WBC"], type: "general" },
  { id: 130, question: "What is the capital of Greece?", answer: ["Athens"], type: "general" },
  { id: 131, question: "Which country is known for kangaroos?", answer: ["Australia"], type: "general" },
  { id: 132, question: "What is the main source of energy for Earth?", answer: ["The Sun", "Sun"], type: "general" },
  { id: 133, question: "Which is the largest coral reef system in the world?", answer: ["Great Barrier Reef"], type: "general" },
  { id: 134, question: "Who wrote 'The Little Prince'?", answer: ["Antoine de Saint-Exupéry", "Saint-Exupéry"], type: "general" },
  { id: 135, question: "What is the capital of Sweden?", answer: ["Stockholm"], type: "general" },
  { id: 136, question: "Which country is known as the Land of a Thousand Lakes?", answer: ["Finland"], type: "general" },
  { id: 137, question: "What is the study of weather called?", answer: ["Meteorology"], type: "general" },
  { id: 138, question: "What is the capital of Norway?", answer: ["Oslo"], type: "general" },
  { id: 139, question: "Which animal is known for building dams?", answer: ["Beaver"], type: "general" },
  { id: 140, question: "Who is known as the King of Pop?", answer: ["Michael Jackson", "Jackson"], type: "general" },
  { id: 141, question: "What is the capital of Switzerland?", answer: ["Bern"], type: "general" },
  { id: 142, question: "Which organ in the human body filters blood?", answer: ["Kidneys", "Kidney"], type: "general" },
  { id: 143, question: "Which country is famous for tulips and windmills?", answer: ["Netherlands","the netherlands", "Holland"], type: "general" },
  { id: 144, question: "What is the capital of Belgium?", answer: ["Brussels"], type: "general" },
  { id: 145, question: "Which planet is known for having a day longer than its year?", answer: ["Venus"], type: "general" },
  { id: 146, question: "Who wrote '1984'?", answer: ["George Orwell", "Orwell"], type: "general" },
  { id: 147, question: "Which sea separates Europe and Africa?", answer: ["Mediterranean Sea", "Mediterranean"], type: "general" },
  { id: 148, question: "What is the capital of Poland?", answer: ["Warsaw"], type: "general" },
  { id: 149, question: "Which animal is known as man's best friend?", answer: ["Dog"], type: "general" },
  { id: 150, question: "What is the capital of Egypt?", answer: ["Cairo"], type: "general" }  
];

window.QUESTIONS = questions;
