let questions = [
  { id: 1, question: "What is the capital city of France?", answer: ["Paris"], type: "general" },
  // { id: 2, question: "Which planet is known as the Red Planet?", answer: ["Mars"], type: "general" },
  // { id: 4, question: "What is the largest ocean on Earth?", answer: ["Pacific Ocean", "Pacific"], type: "general" },
  // { id: 5, question: "In which year did the Titanic sink?", answer: ["1912"], type: "general" },
  // { id: 6, question: "What is the chemical symbol for gold?", answer: ["Au"], type: "general" },
  // { id: 7, question: "Who developed the theory of relativity?", answer: ["Albert Einstein", "Einstein"], type: "general" },
  // { id: 8, question: "Which country hosted the 2016 Summer Olympics?", answer: ["Brazil"], type: "general" },
  // { id: 9, question: "What is the largest mammal in the world?", answer: ["Blue whale", "Whale"], type: "general" },
  // { id: 10, question: "How many continents are there on Earth?", answer: ["7", "seven"], type: "general" },
  // { id: 11, question: "What is the square root of 144?", answer: ["12", "twelve"], type: "general" },
  // { id: 12, question: "Who wrote 'Romeo and Juliet'?", answer: ["William Shakespeare", "Shakespeare"], type: "general" },
  // { id: 13, question: "Which element has the chemical symbol O?", answer: ["Oxygen"], type: "general" },
  // { id: 14, question: "What is the tallest mountain in the world?", answer: ["Mount Everest", "Mt Everest", "Everest"], type: "general" },
  // { id: 15, question: "Which planet is closest to the Sun?", answer: ["Mercury"], type: "general" },
  // { id: 16, question: "What is the smallest prime number?", answer: ["2", "two"], type: "general" },
  // { id: 17, question: "Who was the first person to walk on the Moon?", answer: ["Neil Armstrong", "Armstrong"], type: "general" },
  // { id: 18, question: "Which country is known as the Land of the Rising Sun?", answer: ["Japan"], type: "general" },
  // { id: 19, question: "What is H2O commonly known as?", answer: ["Water"], type: "general" },
  // { id: 20, question: "Which planet has a ring system?", answer: ["Saturn"], type: "general" },
  // { id: 21, question: "What is the currency of the United States?", answer: ["Dollar", "USD", "US Dollar"], type: "general" },
  // { id: 22, question: "Who is the author of 'Harry Potter' series?", answer: ["J.K. Rowling", "JK Rowling", "J K Rowling"], type: "general" },
  // { id: 23, question: "Which gas do plants absorb from the atmosphere?", answer: ["Carbon dioxide", "CO2"], type: "general" },
  // { id: 24, question: "What is the hardest natural substance on Earth?", answer: ["Diamond"], type: "general" },
  // { id: 25, question: "Which organ pumps blood throughout the human body?", answer: ["Heart"], type: "general" },
  // { id: 26, question: "Which ocean is the smallest on Earth?", answer: ["Arctic Ocean", "Arctic"], type: "general" },
  // { id: 27, question: "Who painted the Starry Night?", answer: ["Vincent van Gogh", "Van Gogh"], type: "general" },
  // { id: 28, question: "What is the freezing point of water in Celsius?", answer: ["0", "zero"], type: "general" },
  // { id: 29, question: "Which planet is called the Morning Star?", answer: ["Venus"], type: "general" },
  // { id: 30, question: "What is the main language spoken in Brazil?", answer: ["Portuguese"], type: "general" },
  // { id: 31, question: "What is the capital of Italy?", answer: ["Rome"], type: "general" },
  // { id: 32, question: "Who discovered penicillin?", answer: ["Alexander Fleming", "Fleming"], type: "general" },
  // { id: 33, question: "What is the largest desert in the world?", answer: ["Sahara Desert", "Sahara"], type: "general" },
  // { id: 34, question: "Which instrument has keys, pedals, and strings?", answer: ["Piano"], type: "general" },
  // { id: 35, question: "How many players are on a soccer team on the field?", answer: ["11", "eleven"], type: "general" },
  // { id: 36, question: "What is the chemical symbol for sodium?", answer: ["Na"], type: "general" },
  // { id: 37, question: "Which animal is known as the King of the Jungle?", answer: ["Lion"], type: "general" },
  // { id: 38, question: "Who was the first President of the United States?", answer: ["George Washington", "Washington"], type: "general" },
  // { id: 39, question: "What is the longest river in the world?", answer: ["Nile", "River Nile"], type: "general" },
  // { id: 40, question: "In which country were the Olympic Games invented?", answer: ["Greece"], type: "general" },
  // { id: 41, question: "What color do you get when you mix red and blue?", answer: ["Purple", "Violet"], type: "general" },
  // { id: 42, question: "What part of the plant conducts photosynthesis?", answer: ["Leaf", "Leaves"], type: "general" },
  // { id: 43, question: "How many sides does a hexagon have?", answer: ["Six", "6"], type: "general" },
  // { id: 44, question: "Who wrote 'The Lord of the Rings'?", answer: ["J.R.R. Tolkien", "JRR Tolkien", "Tolkien"], type: "general" },
  // { id: 45, question: "Which ocean lies between Africa and Australia?", answer: ["Indian Ocean", "Indian"], type: "general" },
  // { id: 46, question: "What is the boiling point of water in Celsius?", answer: ["100", "hundred"], type: "general" },
  // { id: 47, question: "Who invented the telephone?", answer: ["Alexander Graham Bell", "Graham Bell", "Bell"], type: "general" },
  // { id: 48, question: "Which country has the maple leaf on its flag?", answer: ["Canada"], type: "general" },
  // { id: 49, question: "What is the largest land animal?", answer: ["Elephant"], type: "general" },
  // { id: 50, question: "Who painted the ceiling of the Sistine Chapel?", answer: ["Michelangelo"], type: "general" },
  // { id: 61, question: "What is the tallest building in the world (as of 2024)?", answer: ["Burj Khalifa", "Khalifa Tower"], type: "general" },
  // { id: 95, question: "Which city is known as the Big Apple?", answer: ["New York City", "New York"], type: "general" },
  // { id: 98, question: "What is the largest coral reef system in the world?", answer: ["Great Barrier Reef", "Barrier Reef"], type: "general" },
  // { id: 99, question: "Who discovered America in 1492?", answer: ["Christopher Columbus", "Columbus"], type: "general" },
  // { id: 143, question: "Which country is home to the Eiffel Tower?", answer: ["France"], type: "general" },
  // { id: 144, question: "What is the largest country in the world by area?", answer: ["Russia", "Russian Federation"], type: "general" },
  // { id: 145, question: "Which natural satellite orbits the Earth?", answer: ["Moon", "The Moon"], type: "general" },
  // { id: 150, question: "Which planet is farthest from the Sun?", answer: ["Neptune"], type: "general" },
];

window.QUESTIONS = questions;
